### ISSUE TITLE
AsyncSeek SeekFrom::Current is not working as expected

### ISSUE THREAD

**Issue by ririsoft** [smol-rs/blocking#10]
Hello,

I have the following test that shows what looks like a bug to me for the implementation of AsyncSeek.
After a read operation `SeekFrom::Current(0)` returns the end of the file, while it should returns the size of read data.

```rust
#[smol_potat::test]
async fn blocking_seek_bug() -> Result<(), futures::io::Error> {
    use blocking::Unblock;
    use futures::io::{AsyncReadExt, AsyncSeekExt, SeekFrom};
    use std::io::Cursor;

    let mut data = Unblock::new(Cursor::new([0u8; 10]));
    let mut buf = [0u8; 4];

    let mut pos = data.seek(SeekFrom::Current(0)).await?;
    // so far so good
    assert_eq!(pos, 0);

    data.read_exact(&mut buf).await?;
    pos = data.seek(SeekFrom::Current(0)).await?;
    // bang ! pos = 10 (end of file)
    assert_eq!(pos, 4);

    Ok(())
}
```
The sync version works:
```rust
#[test]
fn sync_seek_no_bug() -> Result<(), std::io::Error> {
    use std::io::Cursor;
    use std::io::{Read, Seek, SeekFrom};

    let mut data = Cursor::new([0u8; 10]);
    let mut buf = [0u8; 4];

    let mut pos = data.seek(SeekFrom::Current(0))?;
    // so far so good
    assert_eq!(pos, 0);

    data.read_exact(&mut buf)?;
    pos = data.seek(SeekFrom::Current(0))?;
    // so far so good
    assert_eq!(pos, 4);

    Ok(())
}
```

What do you think ?
Cheers.

**Comment by ghost** [comment]
Unfortunately, this is by design. I should document this a bit better. So `Unblock` reads data in advance and this is very important for performance - it makes reading big files 100s of times faster!

**Comment by ririsoft** [comment]
I understand but doesn't this makes `AyncSeek` support useless ? I had to fallback to `async_st::fs::File` personally: I am parsing some MP4 files and seeking is critical feature for performances.

**Comment by ghost** [comment]
Seeking by relative offset does not work correctly, but seeking to an absolute position should work just fine.

**Comment by ririsoft** [comment]
This is good to know and should indeed be documented. My concern then is that this notice will have to be propagated through all the API layers using `blocking`: One can expect to consume `blocking` at low level in their architecture while exposing a `AsyncRead + AsyncSeek` API at higher level. Libraries consuming such APIs would expect `AsyncSeek` behavior to be consistent with `std::io::Sync`, I guess (this is my case at least). Maybe `AsyncSeek` support should be dropped until this is fixed ?

**Comment by ghost** [comment]
If we're going to remove `AsyncSeek` support, then problem still persists. Suppose you read something from a file and then write into it. The cursor will not be positioned at the right location before writing.

**Comment by ghost** [comment]
I added a note to the docs about this.
