### ISSUE TITLE
Locking inner mutex in main loop is effectively single-thread operation

### ISSUE THREAD

**Issue by MOZGIII** [smol-rs/blocking#11]
Hello. It seems like locking the `inner` mutex in the `main_loop`, how it’s currently done, will block all the worker threads except one, effectively only allowing for only a single thread to process tasks.

**Comment by ghost** [comment]
It's true that there is a single mutex all threads share, but note that they don't hold the mutex while running tasks.

**Comment by MOZGIII** [comment]
Don't they? Maybe I'm missing something.

I was looking at

https://github.com/stjepang/blocking/blob/4651a353c2133c209ba84d62defafecadc0aa3cf/src/lib.rs#L203-L236

It looks like the lock is held on to from the beginning of the fn, and then relocked at line 218. But it's still being held for the whole time. It does allow other threads to take over via relocking, but it still looks like at most one thread can hold the lock at a time.

If it's something simple that I don't follow along, could you please explain what's the idea there?

**Comment by MOZGIII** [comment]
Ah, I see, `grow_pool` takes the guard by-value.
Nvm!
