### ISSUE TITLE
Please support configuring the thread limits

### ISSUE THREAD

**Issue by joshtriplett** [smol-rs/blocking#14]
blocking appears to have an internal limit of 500 threads in the thread pool. Please consider providing support for tuning this value, and consider making the default scale with the number of CPUs on the system.

**Comment by ghost** [comment]
Did you perhaps hit the limit of 500 threads? When you say "making the default scale with the number of CPUs on the system", do you mean something like `limit = num_cpus * some_constant`?

As an interesting comparison, Go puts the limit at 10 000 threads. If the limit is exceeded, the process simply gets aborted.

**Comment by mmstick** [comment]
Go's use case is for services on a server handling thousands of requests. It'd be nice to ensure that a desktop application or desktop system service doesn't potentially reach 500 threads running simultaneously.

**Comment by dvc94ch** [comment]
Not sure if 500 is too much for a low powered android device, but in case it causes issues there needs to be a mechanism so that it can be decreased.

**Comment by manifest** [comment]
I would also love to configure the blocking thread pool size using some environment variable, in a similar way it's done for async-std and tokio executors.

I also wonder if there is any way to make `idle_count` and `thread_count` publicly available to observe these values in applications running in production.

**Comment by Byron** [comment]
@taiki-e Is this something you would be OK seeing a contribution for after a minimal version has been sketched out?  Personally I think a start would be to make the `Executor` instantiable to allow the maximum thread count to be configured.

The reason I am thinking about this is that `blocking` seems to be the best candidate _crate_ for unblocking code which can't be fully unblocked to avoid pulling in a full-blown _framework_.

Looking into async-std for example I noticed that it uses the [async-global-executor] which under the hood uses `blocking`. This leaves only `tokio::spawn_blocking(…)` which appears to [have a knob] for adjusting the thread limit.

[async-global-executor]: https://github.com/async-rs/async-global-executor
[have a knob]: https://github.com/tokio-rs/tokio/blob/8efed43fa727e1807c7bc89ac6963a14c2d72c9a/tokio/src/runtime/builder.rs#L245-L245

**Comment by taiki-e** [comment]
Hmm. I'm not clear about what a good solution to this would be.

Adding an `ExecutorBuilder`-like type would not be enough to solve the problem, since the dependencies's code built on top of blocking refers to the global executor.

The approach of using TLS to set something like "current executor" would be easily misused because (unlike tokio) the blocking executor is separated from the normal executor.

EDIT: Using environment variables is not ideal, but it probably works...

**Comment by Byron** [comment]
> Adding an ExecutorBuilder-like type would not be enough to solve the problem, since the dependencies's code built on top of blocking refers to the global executor.

To my mind, having it exposed would allow custom instances of the `blocking` executor to be used by `blocking`-aware implementations, independently of what other `blocking` dependent crates are doing. A typical setup might be that IO is managed by `tokio` while CPU intense or blocking tasks are spawned into an application-controlled `blocking` executor.

Using environment variables to control the limit seems like it would solve an issue too and might already work for many. Maybe this could be a first PR.

**Comment by taiki-e** [comment]
> To my mind, having it exposed would allow custom instances of the `blocking` executor to be used by `blocking`-aware implementations, independently of what other `blocking` dependent crates are doing. A typical setup might be that IO is managed by `tokio` while CPU intense or blocking tasks are spawned into an application-controlled `blocking` executor.

Thanks for the explanation. It seems reasonable to me.

> Using environment variables to control the limit seems like it would solve an issue too and might already work for many. Maybe this could be a first PR.

Agreed. I would accept a PR to do it.

**Comment by Jarema** [comment]
@taiki-e I've created PR applying requested changes.
