### ISSUE TITLE
Is there any way to handle the blocked thread?

### ISSUE THREAD

**Issue by uuhan** [smol-rs/blocking#20]
I am using some blocking functions from external library and in some conditions the function blocks forever.

I wonder if there is a way to handle this condition, I mean, just like to kill the spawned thread?

**Comment by taiki-e** [comment]
Is there a way to handle something like this in std thread handle?

There is a feature in the asynchronous task (spawn) handle that seemingly can handle this kind of stuff, but AFAIK it actually only works with asynchronous tasks.

**Comment by uuhan** [comment]
closed.

There is not way to terminate a blocking thread without killing the entire program.
