### ISSUE TITLE
Remove the `'static` lifetime requirement for `unblock` macro?

### ISSUE THREAD

**Issue by phil-opp** [smol-rs/blocking#4]
The `unblock` macro currently requires the `'static` lifetime for the passed closure. I wonder if that is really necessary because the implicit `await` of the macro should guarantee that the surrounding function lives at least as long as the closure. Or am I missing something here?

Implementation-wise, maybe it's possible to use crossbeam's [scoped threads](https://docs.rs/crossbeam/0.7.3/crossbeam/fn.scope.html) for this.

**Comment by ghost** [comment]
Unfortunately, that is not possible and we can't use scoped threads. To see why, consider:

```rust
async {
    let local_var = "foo".to_string();
    unblock(|| something(&local_var)).await;
}
```

A solution with scoped threads would have to block the main threads until spawned threads complete. But we're not allowed to block inside futures.

Furthermore, we have to assume that the main future (the big `async {}` block here) can be dropped at any time, thus dropping `local_var` and invalidating the reference passed into the `unblock()` closure.

There are probably ways to solve this problem in one way way or another, but I haven't found a satisfying solution without deal-breaking tradeoffs yet.

**Comment by phil-opp** [comment]
Thanks a lot for the explanation, makes complete sense!
