### ISSUE TITLE
Possible deadlocks detected in blocking

### ISSUE THREAD

**Issue by luukvanderduim** [smol-rs/blocking#42]
While looking into (possible) concurrency related issues in a tool I am working on, I ran the static deadlock detector [lockbud](https://github.com/BurtonQin/lockbud/tree/all) and it reports that there may be issues in blocking 1.3.1. 

Here is a gist to [lockbud's output when run on blocking](https://gist.github.com/luukvanderduim/74ac10da9ded9352229494deaa713536)

These may be false positives, but I thought I'd let you know.

**Comment by notgull** [comment]
For ease of lookup, the two "locks" involved are here:

https://github.com/smol-rs/blocking/blob/f89581310d9a9fb7718cccb1664b2b7f70f8ee53/src/lib.rs#L220

...and here:

https://github.com/smol-rs/blocking/blob/f89581310d9a9fb7718cccb1664b2b7f70f8ee53/src/lib.rs#L243

...whose lock appears to come from here:

https://github.com/smol-rs/blocking/blob/f89581310d9a9fb7718cccb1664b2b7f70f8ee53/src/lib.rs#L238

I don't see how this could deadlock. User code is only called when the lock is unlocked. I'll close this issue unless this can be demonstrated with real code.
