### ISSUE TITLE
Implement Seek for BlockOn and AsyncSeek for Unblock

### ISSUE THREAD

**Issue by ririsoft** [smol-rs/blocking#5]
Hello,

During a [smolt issue discussion](https://github.com/stjepang/smol/issues/79#issuecomment-645485379) i raised the need to preserve `std::io::Seek` traits when moving from/out async.

While it is possible to seek through access to the inner `std::io::Seek` with `file.with_mut(|f| f.seek(pos)).await?` it would be more convenient to seek from outer directly : `file.seek(pos).await?`.

Would you consider implementing `Seek` for `BlockOn<T>` when `T: AsyncSeek` and `AsyncSeek` for `Unblock<T>`  when `T: std::io::Seek` please ?

Cheers !

**Comment by ririsoft** [comment]
Hi @stjepang ,

I am wondering wether `AsyncSeek` should be also implemented by [async-dup](https://github.com/stjepang/async-dup) utilities. I have the following:

```rust
/// Badly chosen name ...
pub trait Stream: AsyncRead + AsyncSeek + Sync + Send + Unpin {}

impl<T: AsyncRead + AsyncSeek + Sync + Send + Unpin> Stream for T {}

#[async_trait]
pub trait Repository: std::fmt::Debug + Send + Sync {
    async fn open(&self, url: &str) -> anyhow::Result<Box<dyn Stream + 'static>>;
}

struct LocalRepository;

#[async_trait]
impl Repository for LocalRepository {
    async fn open(&self, url: &str) -> anyhow::Result<Box<dyn Stream + 'static>> {
        let path = url_to_file_path(url);
        let file = Unblock::new(fs::File::open(path)?);
        Ok(Box::new(file))
    }
}
```
But this misses `Sync` properties to be used in async context.
My understanding (I am a beginner in async) is that `async_dup::Mutex` is the way to go but I will loose the `AsyncSeek`.

What do you think ? Should I open an issue for this in `async_dup` ?
Cheers,

**Comment by ghost** [comment]
@ririsoft Published a new version of `async-dup` that implements `AsyncSeek` for its `Arc`, `Mutex`, and `&Mutex`: https://docs.rs/async-dup/1.1.0/async_dup/

**Comment by ririsoft** [comment]
> @ririsoft Published a new version of `async-dup` that implements `AsyncSeek` for its `Arc`, `Mutex`, and `&Mutex`: https://docs.rs/async-dup/1.1.0/async_dup/

It works like a charm, thanks a lot @stjepang ! This was the last piece allowing me to rely only on `futures`, `smolt`, `blocking`, `async-dup`. I dropped my `async-std` dependency. This helped me understand async/await and pinning much better than with higher level crates which bring a lot of magic.

I was wondering also whether you want to implement `AsyncBufRead`. I do not need it, and IMHO I believe building APIs requiring `AsyncBufRead` is not best practice. Buffering should remain an implementation detail.

**Comment by ghost** [comment]
Unfortunately, the interface of `AsyncBufRead` does not allow it: https://github.com/stjepang/async-dup/issues/1
