### ISSUE TITLE
Is there a reason the `Task` type is boxing a future?

### ISSUE THREAD

**Issue by asonix** [smol-rs/blocking#7]
I was looking through this crate's source to see if I could learn anything here that I could implement in actix land and I encountered what seems like redundant code between `unblock` and `Executor::spawn`

unblock:
```rust
let (sender, receiver) = oneshot::channel();
let task = Executor::spawn(async move {
    let _ = sender.send(f());
});
task.await;
receiver.await.expect("future has panicked")
```

spawn:
```rust
let (s, r) = oneshot::channel();
let future = async move {
    let _ = s.send(future.await);
};
...
Box::pin(async { r.await.expect("future has panicked") })
```

The difference here is unblock returns a future that lives on the stack, but spawn returns a future that lives on the heap. The "Task<T>" type alias that is referenced as the return value of `spawn` is only ever created here and only used in the context of calling spawn.

But if it's only created here, and the only thing it ever does is call `await` on a `oneshot::Receiver`, then wouldn't it make just as much sense for the following implementation of Task:

```rust
pin_project! {
    /// Awaits the output of a spawned future.
    pub struct Task<T> {
        #[pin]
        inner: oneshot::Receiver<T>,
    }
}

impl<T> Future for Task<T> {
    type Output = T;

    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<T> {
        let this = self.project();

        match this.inner.poll(cx) {
            Poll::Ready(res) => Poll::Ready(res.expect("future has panicked")),
            Poll::Pending => Poll::Pending,
        }
    }
}
```

So instead of returning 
```rust
Box::pin(async move { r.await.expect("future has panicked") })
```
the spawn method can return
```rust
Task { inner: r }
```

And instead of using an additional oneshot in `unblock`, it could be implemented as
```rust
Executor::spawn(async move { f() }).await
```

Or, could unblock be simplified without needing to remove the Task<T> Boxed future alias?

**Comment by ghost** [comment]
Ha, that's a really neat solution! :) It looks like that could indeed work.

**Comment by asonix** [comment]
Unblock can already be implemented as
```rust
Executor::spawn(async move { f() }).await
```
without changing the Task type, so this issue actually details two different changes.

I thought they might be related due to the boxing of the task future, but I guess not.

**Comment by ghost** [comment]
This is now fixed on the master branch.
