### ISSUE TITLE
invalid std::fs::File::open example

### ISSUE THREAD

**Issue by ririsoft** [smol-rs/blocking#9]
Hello,

I am wondering whether the following example we can find in the documentation is valid:

```rust
block_on(async {
    let input = Unblock::new(File::open("file.txt")?);
    let mut output = Unblock::new(stdout());

    futures::io::copy(input, &mut output).await?;
    io::Result::Ok(())
});
```

Isn't `File::open` a blocking call ? In such case we would have a blocking IO within an `async` block, before `Unblock` is able to move it to a dedicated thread pool. Shouldn't the example be rewritten the following:

```rust
block_on(async {
    let input = Unblock::new(unblock!(File::open("file.txt"))?);
    let mut output = Unblock::new(stdout());

    futures::io::copy(input, &mut output).await?;
    io::Result::Ok(())
});
```

Sorry in advance if i misunderstood the things. While I understand (a little) the `async` concepts, I am still not at ease with the internals.

**Comment by ghost** [comment]
Yes, you're correct! That said, it may be overly pedantic to treat every single file I/O operation as blocking. In my opinion, opening, closing, or reading/writing small files is not really blocking, unless the filesystem is on the network.

It's interesting how C# doesn't even have async methods for opening files, but does have methods for async reading/writing. I think the rationale for that is the same.

**Comment by ririsoft** [comment]
Thank you for the clarification. I understand your point and the need to not be pedantic in the example. It is fine to me to close this issue and people who really care will notice it anyway.

My real life example is the following: I have an USB disk attached to my personal home server running Linux to serve my video files for personal usage. I am using extensively systemd automount and my disk's sleep features to make it go to sleep as much as possible (and thus drastically extending its lifetime and reducing my electric power consumption). However resuming back from sleep takes ages (up to 10s) and can even block for ever because USB is so bad (and the disk is old).

This is why handling the `std::fs::File::open` on the dedicated blocking thread pool maters to me. I will share my code once it is "presentable at minimum", but I can tell you again that smol and blocking are a joy to use :) I have not performed any benchmark so far, but this is a rewrite of a pure `Go` application so I will be interested to see my netdata graphs before and after the migration to the `Rust async` rewrite.

**Comment by ghost** [comment]
[deleted]

**Comment by ririsoft** [comment]
I think you wanted to post on #10 ;-)

**Comment by ghost** [comment]
Yes, sorry!

**Comment by ghost** [comment]
This is now fixed on the master branch.
